apiVersion: v1
kind: Namespace
metadata:
  name: kafka-backup-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-backup-jobs
  namespace: kafka-backup-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-restore-jobs
  namespace: kafka-backup-demo
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-s3-credentials
  namespace: kafka-backup-demo
type: Opaque
stringData:
  access-key-id: minioadmin
  secret-access-key: minioadmin
